export const IpcChannels = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  modelsList: 'models:list',
  healthCheck: 'health:check',
  personasList: 'personas:list',
  chatSend: 'chat:send',
  chatCancel: 'chat:cancel',
  chatToken: 'chat:token',
  chatDone: 'chat:done',
  chatError: 'chat:error',
  conversationsList: 'conversations:list',
  conversationsCreate: 'conversations:create',
  conversationsRename: 'conversations:rename',
  conversationsDelete: 'conversations:delete',
  conversationsGet: 'conversations:get',
  messagesList: 'messages:list',
  dialogPickFolder: 'dialog:pickFolder',
  workspaceOp: 'workspace:op',
  imagesGenerate: 'images:generate',
  imagesGetDataUrl: 'images:getDataUrl',
  imagesDownload: 'images:download',
  imagesSaveToWorkspace: 'images:saveToWorkspace',
  modelStatus: 'model:status',
  orchestratorStep: 'orchestrator:step',
  chatMessagesUpdated: 'chat:messagesUpdated',
} as const;
